---
title: "Dutch Election Observatory Dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: scroll
    smooth_scroll: true
    source_code: embed
    theme: readable
runtime: shiny
---


```{r global, include=FALSE, echo=F, results='hide'}


library(flexdashboard)
knitr::opts_chunk$set(echo = F, message = F, warning = F)

library(shiny)
library(janitor)
library(data.table)
library(magrittr)
library(glue)
library(highcharter)
library(lubridate)
library(knitr)
library(shinyWidgets)
library(tidyverse)
library(htmltools)
# library(apexcharter)

# ggl_ads <- readRDS("data/ggl_ads.RDS")

ggl_aggr <- readRDS("data/ggl_aggr.RDS")
fb_aggr <- readRDS("data/fb_aggr.RDS")



snap_ads <- readRDS("data/snap_ads.RDS")

mapdata <- readRDS("data/mapdata.RDS")


# fb_dat_parties <- readRDS("fb_dat/fb_dat_parties.rds")


# tags$script("https://code.highcharts.com/mapdata/countries/nl/nl-all.js")


source("helpers.R")

# download_data <- T
```

Google Ads {data-icon="fa-google"}
=========================================

Sidebar {.sidebar}
-------------------------------

```{r}

prettyRadioButtons(
   inputId = "plot_type_ggl",
   label = "Select Metric: ",
   choices = c("Number of Ads", "Spent (in EUR)"), 
   selected = "Number of Ads",
   # icon = icon("check"), 
   status = "info",
   animation = "smooth"
)

dutch_parties <- c("D66", "VVD", "GroenLinks", "SP (Socialistische Partij)", "Volt Nederland", "Christen Democratisch Appèl", "Partij van de Arbeid", "FvD")


advertiser_names_ggl <- ggl_aggr$total %>%
  pull(advertiser_name)  

defaults_ggl <- advertiser_names_ggl %>% 
  keep(~magrittr::is_in(.x, dutch_parties))




# renderUI({
# 
#    if (input$plot_type_ggl %in% c("Number of Ads", "Spent (in EUR)")) {
# 
#      # HTML("Show number of ads per advertiser")

     selectInput("total_vs_overtime_ggl",
            label = "Total vs. Over Time: ",
            choices = c("Total", "Over Time"),
            selected = "Total")
     

#    } else if (input$plot_type_ggl == "LOL") {
# 
#      # selectInput("pol_polar",
#      #        label = "Variables of Interest",
#      #        choices = pol_polar_choices %>%
#      #          purrr::discard(~str_detect(.x, "Q10")),
#      #        selected = pol_polar_choices[6])
# 
#    } else if (input$plot_type_ggl == "V5/V5.1") {
# 
#      # selectInput("pol_polar",
#      #        label = "Variables of Interest",
#      #        choices = pol_polar_choices ,
#      #        selected = pol_polar_choices[6])
# 
#    }
# 
# })


selectInput("advertisers__ggl", "Select Advertisers", 
            choices = advertiser_names_ggl, 
            selected = defaults_ggl, multiple = T,
            selectize = TRUE, 
            width = NULL, 
            size = NULL)
```

Column 
-----------------------------------------------------------------------

### Google Ads

```{r}




# debugonce(hc_ggl)

hc_plotter <- possibly(hc_plotter, otherwise = NULL, quiet = F)


 output$ggl_chart <-  shiny::renderUI({
  
  ggl_aggr %>% 
    hc_plotter(filters = input$advertisers__ggl,
           plot_type = input$plot_type_ggl,
           total_vs_overtime = input$total_vs_overtime_ggl, 
           platform = "Google")
  })
 
  htmlOutput('ggl_chart')   

# ggl_aggr$ggl_times

  # ggl_aggr %>%
  #   hc_plotter(filters = dutch_parties,
  #               plot_type = "Number of Ads",
  #               total_vs_overtime = "Over Time",
  #              platform = "Google") %>% list
# 
# # debugonce(hc_ggl)
# # 
# #   ggl_aggr %>% 
# #     hc_aggr_ggl(lvls, filters = defaults_ggl)
#   
#   hc_data %>%
#         hchart("line", hcaes(x = date_range_start, 
#                              y = n, 
#                              group = advertiser_name,
#                              color = color))
```


<!-- ### Ad Counts -->

<!-- ```{r, eval=T} -->
<!-- ad_counts <- ggl_ads  %>% -->
<!--   count(date_range_start, advertiser_name) %>% -->
<!--   mutate(date_range_start = as.Date(date_range_start)) %>% -->
<!--   complete(advertiser_name, date_range_start = seq.Date(min(date_range_start), max(date_range_start), by="day"), fill = list(n = 0)) -->

<!-- ad_counts %>% -->
<!--   hchart("line", hcaes(x = date_range_start, y = n, group = advertiser_name)) %>% -->
<!--     hc_title( -->
<!--       text = "" -->
<!--     ) %>% -->
<!--     hc_yAxis( -->
<!--       align = "left", -->
<!--       title = list(text = "Number of Ads") -->
<!--     ) %>% -->
<!--     hc_xAxis( -->
<!--       align = "left", -->
<!--       title = list(text = "Start Date of Ad") -->
<!--     ) %>% -->
<!--     hc_exporting( -->
<!--       enabled = TRUE -->
<!--     ) -->
<!-- ``` -->


<!-- ### Ad Impressions I -->

<!-- ```{r} -->

<!-- heatmap_impressions <- ggl_ads %>%  -->
<!--   count(date_range_start, advertiser_name, impressions) %>% -->
<!--   mutate(date_range_start = as.Date(date_range_start)) %>%  -->
<!--   # complete(advertiser_name, impressions, date_range_start = seq.Date(min(date_range_start), max(date_range_start), by="day"), fill = list(n = 0))%>%  -->
<!--   mutate(impressions2 = fct_relevel(impressions, c("≤ 10k", "10k-100k", "100k-1M")) %>% as.numeric) -->

<!-- hchart( -->
<!--   heatmap_impressions,  -->
<!--   "bubble",  -->
<!--   hcaes( -->
<!--     x = date_range_start, -->
<!--     y = n,  -->
<!--     size = impressions2, -->
<!--     group = advertiser_name -->
<!--     ),  -->
<!-- maxSize = '10%' -->
<!--   ) %>% -->
<!--     hc_title( -->
<!--       text = "" -->
<!--     ) %>% -->
<!--     hc_yAxis( -->
<!--       align = "left", -->
<!--       title = list(text = "Number of Ads") -->
<!--     ) %>%  -->
<!--     hc_xAxis( -->
<!--       align = "left", -->
<!--       title = list(text = "Start Date of Ad") -->
<!--     ) %>%  -->
<!--     hc_exporting( -->
<!--       enabled = TRUE -->
<!--     )  -->
<!-- ``` -->


<!-- ### Ad Impressions II -->

<!-- ```{r, eval = T} -->

<!-- heatmap_impressions <- ggl_ads %>%  -->
<!--   count(advertiser_name, impressions) %>% -->
<!--   complete(advertiser_name, impressions, fill = list(n = 0)) %>%  -->
<!--   mutate(impressions = fct_relevel(impressions, c("≤ 10k", "10k-100k", "100k-1M")))%>%  -->
<!--   group_by(advertiser_name) %>%  -->
<!--   mutate(perc = round(n/sum(n)*100, 2))  -->

<!-- fntltp <- JS("function(){ -->
<!--   return this.point.x + ' ' +  this.series.yAxis.categories[this.point.y] + ': ' + this.point.value; -->
<!-- }") -->

<!-- hchart( -->
<!--   heatmap_impressions,  -->
<!--   "heatmap",  -->
<!--   hcaes( -->
<!--     x = impressions, -->
<!--     y = advertiser_name,  -->
<!--     value = perc -->
<!--     ) -->
<!--   ) %>% -->
<!--   hc_colorAxis( -->
<!--     stops = color_stops(4, viridisLite::inferno(4, direction = -1)) -->
<!--   ) %>% -->
<!--     hc_title( -->
<!--       text = "" -->
<!--     ) %>% -->
<!--     hc_yAxis( -->
<!--       align = "left", -->
<!--       title = list(text = "Advertiser Name") -->
<!--     ) %>%  -->
<!--     hc_xAxis( -->
<!--       align = "left", -->
<!--       title = list(text = "Impressions") -->
<!--     ) %>%  -->
<!--     hc_exporting( -->
<!--       enabled = TRUE -->
<!--     )  -->
<!-- ``` -->

<!-- ### Gender Targeting -->

```{r}
ggl_ads %>%
  mutate(gender_targeting = ifelse(str_detect(gender_targeting, "Male") & str_detect(gender_targeting, "Female"), "Not targeted", gender_targeting)) %>%
  count(advertiser_name, gender_targeting) %>%
  group_by(advertiser_name) %>%
  mutate(perc = round(n/sum(n)*100, 2)) 


  hchart("bar", hcaes(x = advertiser_name, y = perc, group = gender_targeting))%>%
    hc_xAxis(
      align = "left",
      title = list(text = "Advertiser Name")
    ) %>%
    hc_yAxis(
      align = "left",
      title = list(text = "Percentage of Ads")
    ) %>%
    hc_exporting(
      enabled = TRUE
    )
```


<!-- ### Age Targeting -->

```{r}
# ggl_ads %>%
#   mutate(age_targeting2 = case_when(
#     str_detect(age_targeting, "18-24, 25-34, 35-44, 45-54, 55-64, ≥65") ~ "Not targeted",
#     T ~ age_targeting
#   )) %>%
#   count(advertiser_name, age_targeting2) %>%
#   complete(advertiser_name, age_targeting2, fill = list(n = 0)) %>%
#   group_by(advertiser_name) %>%
#   mutate(perc = round(n/sum(n)*100, 2)) %>%
  hchart("bar", hcaes(x = advertiser_name, y = perc, group = age_targeting2)) %>%
    hc_xAxis(
      align = "left",
      title = list(text = "Advertiser Name")
    ) %>%
    hc_yAxis(
      align = "left",
      title = list(text = "Percentage of Ads")
    ) %>%
    hc_exporting(
      enabled = TRUE
    )
```


<!-- ### Geo Targeting -->

```{r}
ggl_ads %>%
  mutate(geo_targeting_included = case_when(
    str_count(geo_targeting_included, ",") >= 11 ~ "Not targeted",
    str_detect(geo_targeting_included, "Netherlands") ~ "Not targeted",
    T ~ geo_targeting_included
  )) %>%
  count(advertiser_name, geo_targeting_included) %>%
  complete(advertiser_name, geo_targeting_included, fill = list(n = 0)) %>%
  group_by(advertiser_name) %>%
  mutate(perc = round(n/sum(n)*100, 2)) %>%
  hchart("bar", hcaes(x = advertiser_name, y = perc, group = geo_targeting_included)) %>%
    hc_xAxis(
      align = "left",
      title = list(text = "Advertiser Name")
    ) %>%
    hc_yAxis(
      align = "left",
      title = list(text = "Percentage of Ads")
    ) %>%
    hc_exporting(
      enabled = TRUE
    )
```


Facebook {data-icon="fa-facebook-square"}
=========================================

<!-- Metrics {data-icon="fa-facebook-square" data-navmenu="Facebook"} -->
<!-- ========================================= -->

Sidebar {.sidebar}
-------------------------------

```{r}

prettyRadioButtons(
   inputId = "plot_type_fb",
   label = "Select Metric: ",
   choices = c("Number of Ads", "Spent (in EUR)", "Impressions", "Targeted Ads"), 
   selected = "Number of Ads",
   # icon = icon("check"), 
   status = "info",
   animation = "smooth"
)

  dutch_parties_fb <- c("VVD", "D66", "Forum voor Democratie -FVD", "SP", "GroenLinks", "Volt Nederland", "Partij van de Arbeid (PvdA)", "CDA", "Partij voor de Dieren", "ChristenUnie")


advertiser_names_fb <- fb_aggr$times %>%
  pull(advertiser_name) %>% 
  unique()

defaults_fb <- advertiser_names_fb %>% 
  keep(~magrittr::is_in(.x, dutch_parties_fb))




renderUI({

   if (input$plot_type_fb %in% c("Number of Ads", "Spent (in EUR)", "Impressions")) {

     # HTML("Show number of ads per advertiser")

     selectInput("total_vs_overtime_fb",
            label = "Total vs. Over Time: ",
            choices = c("Total", "Over Time"),
            selected = "Total")
     

   } else if (input$plot_type_fb == "Targeted Ads") {

     selectInput("targeting_fb",
            label = "Target",
            choices = c("Geotargeting"),
            selected = "Geotargeting")

   } else if (input$plot_type_ggl == "V5/V5.1") {

     # selectInput("pol_polar",
     #        label = "Variables of Interest",
     #        choices = pol_polar_choices ,
     #        selected = pol_polar_choices[6])

   }

})



# renderUI({
# 
#    if (input$plot_type_fb %in% c("Number of Ads", "Spent (in EUR)", "Impressions")) {

     # HTML("Show number of ads per advertiser")

selectInput("advertisers__fb", "Select Advertisers", 
            choices = advertiser_names_fb, 
            selected = defaults_fb, multiple = T,
            selectize = TRUE, 
            width = NULL, 
            size = NULL)
     

#    } else if (input$plot_type_fb == "Targeted Ads") {
#      
#      # my_max <- 3
#      # my_min <- 1
# 
# selectInput("advertisers__fb", "Select Advertisers (please don't select more than 3)", 
#             choices = advertiser_names_fb, 
#             selected = defaults_fb[1:3], multiple = T,
#             selectize = TRUE, 
#             width = NULL, 
#             size = NULL)
#      
#   #   observe({
#   #   if(length(input$advertisers_fb) > my_max){
#   #     updateCheckboxGroupInput(session, "advertisers__fb", selected= tail(input$advertisers__fb,my_max))
#   #   }
#   #   if(length(input$advertisers__fb) < my_min){
#   #     updateCheckboxGroupInput(session, "advertisers__fb", selected= "a1")
#   #   }
#   # })
# 
#    } else if (input$plot_type_ggl == "V5/V5.1") {
# 
#      # selectInput("pol_polar",
#      #        label = "Variables of Interest",
#      #        choices = pol_polar_choices ,
#      #        selected = pol_polar_choices[6])
# 
#    }
# 
# })



```

Column 
-----------------------------------------------------------------------

### Facebook Ads

```{r}

# debugonce(hc_ggl)

# hc_plotter <- possibly(hc_plotter, otherwise = NULL, quiet = F)

# shiny::reactiveUI({
#   
#   if(input$plot_type_fb != "Targeted Ads"){
  
 output$fb_chart <-  shiny::renderUI({

    fb_aggr %>%
      hc_plotter(filters = input$advertisers__fb,
             plot_type = input$plot_type_fb,
             total_vs_overtime = input$total_vs_overtime_fb,
             targeting = input$targeting_fb,
             platform = "Facebook")
  })
  # } else if (input$plot_type_fb == "Targeted Ads") {
  # output$chart1 <- renderUI({
  #   fb_aggr %>% 
  #     hc_plotter(filters = input$advertisers__fb,
  #            plot_type = input$plot_type_fb,
  #            total_vs_overtime = input$total_vs_overtime_fb, 
  #            targeting = input$targeting_fb,
  #            platform = "Facebook")
  # })

     # div(style = 'height: 500px; overflow-y: auto; ', htmlOutput('fb_chart') )
     
    
htmlOutput('fb_chart')
  # }
  
  
# })



  # fb_aggr %>% 
  #   hc_plotter(filters = "D66",
  #          plot_type = "Targeted Ads",
  #          total_vs_overtime = "Total", 
  #          targeting = "Geotargeting",
  #          platform = "Facebook")
# debugonce(hc_plotter)
#   fb_aggr %>%
#     hc_plotter(filters = "D66",
#            plot_type = "Impressions",
#            total_vs_overtime = "Total",
#            targeting = "Geotargeting",
#            platform = "Facebook")
```



Snapchat {data-icon="fa-snapchat-ghost"}
=========================================

Column {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Ad Counts


```{r}


ad_counts <- snap_ads  %>% 
  count(start_date, paying_advertiser_name) %>%
  mutate(start_date = as.Date(start_date)) %>% 
  complete(paying_advertiser_name, start_date = seq.Date(min(start_date), max(start_date), by="day"), fill = list(n = 0))

ad_counts %>% 
  hchart("line", hcaes(x = start_date, y = n, group = paying_advertiser_name)) %>%
    hc_title(
      text = ""
    ) %>%
    hc_yAxis(
      align = "left",
      title = list(text = "Number of Ads")
    ) %>% 
    hc_xAxis(
      align = "left",
      title = list(text = "Start Date of Ad")
    ) %>% 
    hc_exporting(
      enabled = TRUE
    ) 
```


### Ad Impressions


```{r}


ad_impressions <- snap_ads  %>% 
  group_by(start_date, paying_advertiser_name) %>% 
  summarize(n = n(),
            impressions = sum(impressions)) %>% 
  mutate(start_date = lubridate::as_date(start_date)) 

hchart(
  ad_impressions, 
  "bubble", 
  hcaes(
    x = start_date,
    y = n, 
    size = impressions,
    group = paying_advertiser_name
    ), 
maxSize = '10%'
  ) %>%
    hc_title(
      text = ""
    ) %>%
    hc_yAxis(
      align = "left",
      title = list(text = "Number of Ads")
    ) %>% 
    hc_xAxis(
      align = "left",
      title = list(text = "Start Date of Ad")
    ) %>% 
    hc_exporting(
      enabled = TRUE
    ) 
```
