---
title: "Tidy Template"
author: "Fabio Votta"
date: "The Date"
output: html_document
---

This script is about:



## Packages and Folders

```{r}
# Install these packages if you don't have them yet
# if (!require("pacman")) install.packages("pacman")
# devtools::install_github("favstats/tidytemplate")

pacman::p_load(tidyverse, tidytemplate, rvest, data.table, janitor)

# Creates folders
# tidytemplate::data_dir()
# tidytemplate::images_dir()
```


## Load Data

```{r, data}

get_ggl_data <- function() {
  ggl_link <- "https://storage.googleapis.com/transparencyreport/google-political-ads-transparency-bundle.zip"
  
  ggl_file <- "data/ggl.zip"
  
  download.file(ggl_link, ggl_file, mode="wb")
  unzip(ggl_file, exdir = "data")
  
  unlink(ggl_file)
  
  dir("data/google-political-ads-transparency-bundle", full.names =   T) %>% 
    discard(~str_detect(.x,"creative")) %>% 
    walk(file.remove)  
  
  dutch_parties <- c("D66", "VVD", "GroenLinks", "SP (Socialistische Partij)", "Volt Nederland", "Christen Democratisch Appèl", "Partij van de Arbeid")
  
  ggl_ads <- data.table::fread("data/google-political-ads-transparency-bundle/google-political-ads-creative-stats.csv") %>% 
    # filter(str_detect(Regions, "NL")) %>%
  janitor::clean_names() %>% 
  filter(advertiser_name %in% dutch_parties) %>%
  filter(date_range_start >= as.Date("2020-09-01"))
  
  return(ggl_ads)
}

ggl_ads <- get_ggl_data()

tidytemplate::save_it(ggl_ads)

  
gggl <- data.table::fread("data/google-political-ads-transparency-bundle/google-political-ads-creative-stats.csv") %>% 
  janitor::clean_names()

gggl %>%
  mutate(campaign = case_when(
    advertiser_name == "STOP REPUBLICANS" ~ NA_character_,
    str_detect(advertiser_name, "REPUBLICAN|GOP|TRUMP") ~ "TRUMP/REPUBLICAN",
    str_detect(advertiser_name, "DEMOCRAT|DNC|BIDEN") ~ "BIDEN/DEMOCRAT",
    T ~ "Other"
  ))  %>% 
  filter(campaign != "Other") %>% 
  filter(date_range_start >= as.Date("2020-05-01")) %>% 
  filter(ad_type == "Video") %>% 
  count(age_targeting, campaign, sort = T) %>% View
```
```{r}

ggl_ads  %>% 
  count(date_range_start, advertiser_name) %>%
  mutate(date_range_start = as.Date(date_range_start)) %>% 
  complete(advertiser_name, date_range_start = seq.Date(min(date_range_start), max(date_range_start), by="day"), fill = list(n = 0)) %>% 
  ggplot(aes(date_range_start, n, color = advertiser_name)) +
  geom_line()

ggl_ads %>% count(advertiser_name, sort = T)
```

```{r}
      get_mid <- function(spend_upper_bound, spend_lower_bound) {
        # (spend_upper_bound-spend_lower_bound)/2+spend_lower_bound
        (spend_upper_bound+spend_lower_bound)/2
      }

get_mid(99999, 20)

median(c(99999, 20))

(99999+20)/2
library(highcharter)

color_dat <- tibble(
  color = c("#00b13d", "#80c31c", "#cd503e", "#008067"),
  advertiser_name = c("D66", "GroenLinks", "VVD", "Christen Democratisch Appèl"))

ggl_aggr <- ggl_ads %>% 
  group_by(advertiser_name) %>% 
  summarise(spend_range_min = sum(spend_range_min_eur),
            spend_range_max = sum(spend_range_max_eur),
            spend_range_mid = sum(get_mid(spend_range_max_eur, spend_range_min_eur)),
            n = n()) %>% 
  left_join(color_dat)

lvls <- ggl_aggr %>% 
  mutate(advertiser_name = fct_reorder(advertiser_name, spend_range_mid)) %>% 
  pull(advertiser_name) %>% 
  levels() %>% 
  rev()

ggl_aggr %>% 
  hchart(
    type = "errorbar",
    hcaes(
      x = advertiser_name,
      low = spend_range_min, 
      high = spend_range_max,
      color = color),
      tooltip = list(pointFormat = "<b>Lower bound:</b> {point.spend_range_min}€<br><b>Mid point:</b> {point.spend_range_mid}€<br><b>Upper bound:</b> {point.spend_range_max}€")) %>%
  hc_add_series(
    data = ggl_aggr, 
    type = "point",
    hcaes(
      x = advertiser_name, 
      y = spend_range_mid,
      color = color
      ),
      name = "Euros spent",
      tooltip = list(pointFormat = "<b>Lower bound:</b> {point.spend_range_min}€<br><b>Mid point:</b> {point.spend_range_mid}€<br><b>Upper bound:</b> {point.spend_range_max}€"))%>%
  hc_yAxis(reversed = F, min = 0, title = list(text = "€ spent on Ads"))  %>% 
  hc_xAxis(categories = lvls, title = list(text = "")) %>% 
  hc_chart(inverted = TRUE)  %>%
  hc_title(
    text = "Total spending on Google ads"
    ) %>%
  hc_subtitle(
    text = "Google only provides lower & upper bound of Euros spend"
  ) %>% 
  hc_credits(
    enabled = T,
    text = "Source: Google Transparency Report. Ads since September 1st 2020.",
    href = "https://transparencyreport.google.com/political-ads/region/NL"
  )
```


## Analysis / Dataviz

```{r, analysis}
ggl_ads %>% 
  count(geo_targeting_included)

heatmap_impressions <- ggl_ads %>% 
  count(date_range_start, advertiser_name, impressions) %>%
  mutate(date_range_start = as.Date(date_range_start)) %>% 
  # complete(advertiser_name, impressions, date_range_start = seq.Date(min(date_range_start), max(date_range_start), by="day"), fill = list(n = 0))%>% 
  mutate(impressions2 = fct_relevel(impressions, c("≤ 10k", "10k-100k", "100k-1M")) %>% as.numeric)

hchart(
  heatmap_impressions, 
  "bubble", 
  hcaes(
    x = date_range_start,
    y = n, 
    size = impressions2,
    group = advertiser_name
    ), 
maxSize = '10%'
  ) %>%
    hc_title(
      text = ""
    ) %>%
    hc_yAxis(
      align = "left",
      title = list(text = "Number of Ads")
    ) %>% 
    hc_xAxis(
      align = "left",
      title = list(text = "Date (daily)")
    ) %>% 
    hc_exporting(
      enabled = TRUE
    ) 

```
```{r}
ggl_ads %>% 
  mutate(gender_targeting = ifelse(str_detect(gender_targeting, "Male") & str_detect(gender_targeting, "Female"), "Not targeted", gender_targeting)) %>% 
  count(advertiser_name, gender_targeting) %>% 
  group_by(advertiser_name) %>% 
  mutate(perc = round(n/sum(n)*100, 2)) %>% 
  hchart("bar", hcaes(x = advertiser_name, y = perc, group = gender_targeting))
  
```

```{r}
ggl_ads %>% 
  # mutate(gender_targeting = ifelse(str_detect(gender_targeting, "Male") & str_detect(gender_targeting, "Female"), "Not targeted", gender_targeting)) %>% 
  mutate(age_targeting2 = case_when(
    str_detect(age_targeting, "18-24, 25-34, 35-44, 45-54, 55-64, ≥65") ~ "Not targeted",
    T ~ age_targeting
  )) %>% 
  count(advertiser_name, age_targeting2) %>% 
  complete(advertiser_name, age_targeting2, fill = list(n = 0)) %>%
  group_by(advertiser_name) %>% 
  mutate(perc = round(n/sum(n)*100, 2)) %>% 
  hchart("bar", hcaes(x = advertiser_name, y = perc, group = age_targeting2))
  
```

```{r}
ggl_ads %>% 
  mutate(geo_targeting_included = case_when(
    str_count(geo_targeting_included, ",") >= 11 ~ "Not targeted",
    str_detect(geo_targeting_included, "Netherlands") ~ "Not targeted",
    T ~ geo_targeting_included
  )) %>% 
  count(advertiser_name, geo_targeting_included) %>% 
  complete(advertiser_name, geo_targeting_included, fill = list(n = 0)) %>%
  group_by(advertiser_name) %>% 
  mutate(perc = round(n/sum(n)*100, 2)) %>% 
  hchart("bar", hcaes(x = advertiser_name, y = perc, group = geo_targeting_included))
  
 	
heatmap_impressions <- ggl_ads %>% 
  count(advertiser_name, impressions) %>%
  complete(advertiser_name, impressions, fill = list(n = 0)) %>% 
  mutate(impressions = fct_relevel(impressions, c("≤ 10k", "10k-100k", "100k-1M")))%>% 
  group_by(advertiser_name) %>% 
  mutate(perc = round(n/sum(n)*100, 2)) 

fntltp <- JS("function(){
  return this.point.x + ' ' +  this.series.yAxis.categories[this.point.y] + ': ' + this.point.value;
}")

hchart(
  heatmap_impressions, 
  "heatmap", 
  hcaes(
    x = impressions,
    y = advertiser_name, 
    value = perc
    )
  ) %>%
  hc_colorAxis(
    stops = color_stops(4, viridisLite::inferno(4, direction = -1))
  ) %>%
    hc_title(
      text = ""
    ) %>%
    hc_yAxis(
      align = "left",
      title = list(text = "Advertiser Name")
    ) %>% 
    hc_xAxis(
      align = "left",
      title = list(text = "Impressions")
    ) %>% 
    hc_exporting(
      enabled = TRUE
    ) 
```





```{r}

```


```{r}
devtools::install_github("facebookresearch/Radlibrary")


```
```{r}
library(Radlibrary)
library(httr)

get_fb_ads <- function() {
  
token <- token_get()$token


#link to fb api
my_link<- "https://graph.facebook.com"

#define fields you are interested in
search_fields=c("ad_creation_time", 
                "ad_delivery_start_time",
                "ad_delivery_stop_time",
                "ad_creative_link_caption",
                "ad_creative_link_description",
                "ad_creative_link_title",
                "currency",
                "ad_creative_body", 
                "page_id",
                "page_name",
                "spend",
                "demographic_distribution",
                "funding_entity",
                "impressions",
                "region_distribution") %>% 
  stringr::str_c(., collapse=", ")

#get the data from the first 'page' of data the api provides
page_one_response <- GET(my_link,
                         path = "/ads_archive",
                         query = list(access_token = token,
                                      limit=100,
                                      ad_active_status="ALL",
                                      search_terms="''",
                                      impression_condition = 'HAS_IMPRESSIONS_LAST_7_DAYS',
                                      fields=search_fields,
                                      # token = token,
                                      ad_reached_countries="NL"))
page_one_content<- content(page_one_response)

x <- tibble(data=page_one_content$data)
df_imp <- x %>% 
  unnest_wider(data) 

#get the link refering to the next page
next_link <- page_one_content$paging$`next`

page <- 1

#iterate over all pages until there is no further page
while(length(next_link)>0) {
# while(T) {
  
  print(page)
  
  next_response <- GET(next_link)
  next_content<- content(next_response)
  
  y <- tibble(data=next_content$data)
  df_next <- y %>% 
    unnest_wider(data) 
  
  df_imp <- bind_rows(df_imp, df_next)  
  
  next_link <- next_content$paging$`next`
  
  page <- page + 1
  
}

dutch_parties <- c("VVD", "D66", "Forum voor Democratie -FVD", "SP", "GroenLinks", "Volt Nederland", "Partij van de Arbeid (PvdA)", "CDA", "Partij voor de Dieren", "ChristenUnie")

fb_dat <- readRDS("fb_dat/fb_dat.rds")

fb_dat <- df_imp %>% 
  bind_rows(fb_dat) %>% 
  distinct(id, .keep_all = T)

saveRDS(fb_dat, "fb_dat/fb_dat.rds")

fb_dat_parties <- fb_dat %>% 
  mutate(ad_delivery_start_time = as.Date(ad_delivery_start_time)) %>% 
  filter(ad_delivery_start_time >= as.Date("2020-09-01")) %>% 
  filter(page_name %in% dutch_parties) 

saveRDS(fb_dat_parties, "fb_dat/fb_dat_parties.rds")

return(fb_dat)

}
```


```{r}
ad_counts <- fb_dat_parties  %>% 
  count(ad_delivery_start_time, page_name) %>%
  mutate(ad_delivery_start_time = as.Date(ad_delivery_start_time)) %>% 
  complete(page_name, ad_delivery_start_time = seq.Date(min(ad_delivery_start_time), max(ad_delivery_start_time), by="day"), fill = list(n = 0))

ad_counts %>% 
  hchart("line", hcaes(x = ad_delivery_start_time, y = n, group = page_name)) %>%
    hc_title(
      text = ""
    ) %>%
    hc_yAxis(
      align = "left",
      title = list(text = "Number of Ads")
    ) %>% 
    hc_xAxis(
      align = "left",
      title = list(text = "Start Date of Ad")
    ) %>% 
    hc_exporting(
      enabled = TRUE
    ) 
```

```{r}
fb_dat <- readRDS("fb_dat/fb_dat.rds")

      hc_plot <- hc_data %>%
        hchart("line", hcaes(x = date_range_start, 
                             y = n, 
                             group = advertiser_name,
                             color = color)) %>%
        hc_title(
          text = title_text
        ) %>%
        hc_yAxis(
          align = "left",
          title = list(text = "Number of Ads")
        ) %>%
        hc_xAxis(
          align = "left",
          title = list(text = "Start Date of Ad")
        ) %>% 
        hc_colors(unique(hc_data$color))
```
```{r}
dutch_parties <- c("VVD", "D66", "Forum voor Democratie -FVD", "SP", "GroenLinks", "Volt Nederland", "Partij van de Arbeid (PvdA)", "CDA", "Partij voor de Dieren", "ChristenUnie")


  color_dat <- tibble(
    color = c("#00b13d", "#80c31c", "#cd503e", "#008067", "#6f2421", "#e3101c", "#e01003", "#036b2c", "#02a6e9", "#562883"),
    advertiser_name = c("D66", "GroenLinks", "VVD", "CDA", "Forum voor Democratie -FVD", "Partij van de Arbeid (PvdA)", "SP", "Partij voor de Dieren", "ChristenUnie", "Volt Nederland"))

  fb_total <- fb_dat %>% 
    mutate(date_range_start = as.Date(ad_delivery_start_time)) %>%
    filter(date_range_start >= as.Date("2020-09-01")) %>% 
    unnest_wider(spend, names_sep = "_") %>%
    unnest_wider(impressions, names_sep = "_") %>%
    mutate_at(vars(spend_lower_bound, spend_upper_bound, impressions_lower_bound, impressions_upper_bound), as.numeric) %>% 
    rename(advertiser_name = page_name) %>% 
    # drop_na(spend_lower_bound, spend_upper_bound, impressions_lower_bound, impressions_upper_bound) %>% 
    mutate(impressions_lower_bound = case_when(
      is.na(impressions_upper_bound) ~ 0, 
      is.na(impressions_lower_bound) ~ 0,
      T ~ impressions_lower_bound)) %>% 
    mutate(impressions_upper_bound = case_when(
      is.na(impressions_upper_bound) ~ 0, 
      is.na(impressions_lower_bound) ~ 0,
      T ~ impressions_upper_bound)) %>% 
    group_by(advertiser_name) %>% 
    summarise(spend_range_min = sum(spend_lower_bound),
              spend_range_max = sum(spend_upper_bound),
              spend_range_mid = sum(get_mid(spend_lower_bound, spend_upper_bound)),
              impressions_range_min = sum(impressions_lower_bound),
              impressions_range_max = sum(impressions_upper_bound),
              impressions_range_mid = sum(get_mid(impressions_lower_bound, impressions_upper_bound)),
              n = n()) %>% 
    ungroup() %>% 
    left_join(color_dat)  %>% 
    assign_colors()
  
  tidytemplate::save_it(fb_total)
  
fb_times <- fb_dat %>% 
    mutate(date_range_start = as.Date(ad_delivery_start_time)) %>%
    filter(date_range_start >= as.Date("2020-09-01")) %>% 
    unnest_wider(spend, names_sep = "_") %>%
    unnest_wider(impressions, names_sep = "_") %>%
    mutate_at(vars(spend_lower_bound, spend_upper_bound, impressions_lower_bound, impressions_upper_bound), as.numeric) %>% 
    rename(advertiser_name = page_name) %>% 
    # drop_na(spend_lower_bound, spend_upper_bound, impressions_lower_bound, impressions_upper_bound) %>% 
    group_by(date_range_start, advertiser_name) %>% 
    summarise(spend_range_min = sum(spend_lower_bound),
              spend_range_max = sum(spend_upper_bound),
              spend_range_mid = sum(get_mid(spend_lower_bound, spend_upper_bound)),
              impressions_range_min = sum(impressions_lower_bound),
              impressions_range_max = sum(impressions_upper_bound),
              impressions_range_mid = sum(get_mid(impressions_lower_bound, impressions_upper_bound)),
              n = n()) %>% 
    ungroup() %>% 
    complete(advertiser_name, date_range_start = seq.Date(min(date_range_start), max(date_range_start), by="day"), fill = list(n = 0, spend_range_min = 0, spend_range_mid = 0, spend_range_max = 0, impressions_range_min = 0, impressions_range_mid = 0, impressions_range_max = 0)) %>% 
    left_join(color_dat) %>% 
    assign_colors() 


# fb_dat

  fb_aggr <- list(total = fb_total, times = fb_times)
  
  tidytemplate::save_it(fb_aggr)
```

### Targeting

```{r}
unnest_it <- function(x) {
   x   %>% 
  unnest_longer(demographic_distribution) %>% 
  unnest_wider(demographic_distribution)
}

unnest_dems <- function(x) {
  cat(glue::glue("{x$row_number} out of {nrow(age_gender_targeted_raw)} ({round(100*x$row_number/nrow(age_gender_targeted_raw), 2)}%)\n\n"))
  x %>% 
  pull(demographic_distribution) %>% 
  flatten() %>% 
  map_dfr(flatten) %>% 
  mutate(id = x$id)
}

age_gender_targeted_raw <- fb_dat %>% 
  mutate(start_time = lubridate::as_datetime(ad_delivery_start_time) %>% lubridate::floor_date("day")) %>% 
  mutate(start_time = as.Date(start_time))

age_gender_targeted <- age_gender_targeted_raw %>% 
  mutate(row_number = 1:n()) %>% 
  split(1:nrow(.)) %>% 
  map_dfr(unnest_dems) %>% 
  right_join(age_gender_targeted_raw)
```


```{r}
age_gender_targeted  %>% 
  filter(page_name %in% dutch_parties) %>% 
    mutate(date_range_start = as.Date(ad_delivery_start_time)) %>%
    filter(date_range_start >= as.Date("2020-09-01")) %>% 
  mutate(percentage = as.numeric(percentage)) %>% 
  mutate(gender_age = paste(gender, age)) %>% 
  filter(!str_detect(gender_age, "unknown")) %>% 
  filter(!str_detect(gender_age, "13-17")) %>% 
  complete(gender, age, fill = list(percentage = 0)) %>% 
  ggplot(aes(gender_age, percentage)) +
  geom_boxplot() +
  theme_minimal() +
  facet_wrap(~page_name, ncol = 3) +
  coord_flip() 




age_gender_targeted  %>% 
  filter(page_name %in% dutch_parties) %>% 
  mutate(date_range_start = as.Date(ad_delivery_start_time)) %>%
  filter(date_range_start >= as.Date("2020-09-01")) %>% 
  mutate(percentage = as.numeric(percentage)) %>% 
  mutate(gender_age = paste(gender, age)) %>% 
  filter(!str_detect(gender_age, "unknown")) %>% 
  filter(!str_detect(gender_age, "13-17")) %>% 
  complete(gender, age, fill = list(percentage = 0)) %>% 
  group_by(id, gender, page_name) %>% 
  summarize(percentage = sum(percentage)) %>% 
  ggplot(aes(gender, percentage)) +
  geom_boxplot() +
  theme_minimal() +
  facet_wrap(~page_name, ncol = 3) +
  coord_flip() 

age_gender_targeted  %>% 
  filter(page_name %in% dutch_parties) %>% 
  mutate(date_range_start = as.Date(ad_delivery_start_time)) %>%
  filter(date_range_start >= as.Date("2020-09-01"))  %>% 
  mutate(percentage = as.numeric(percentage)) %>% 
  mutate(gender_age = paste(gender, age)) %>% 
  filter(!str_detect(gender_age, "unknown")) %>% 
  filter(!str_detect(gender_age, "13-17")) %>% 
  complete(gender, age, fill = list(percentage = 0)) %>% 
  group_by(id, age, page_name) %>% 
  summarize(percentage = sum(percentage)) %>% 
  ggplot(aes(age, percentage)) +
  geom_boxplot() +
  theme_minimal() +
  facet_wrap(~page_name, ncol = 3) +
  coord_flip() 


gender_targeted_plot <- age_gender_targeted  %>% 
  filter(page_name %in% dutch_parties) %>% 
  mutate(date_range_start = as.Date(ad_delivery_start_time)) %>%
  filter(date_range_start >= as.Date("2020-09-01")) %>% 
  mutate(percentage = as.numeric(percentage)) %>% 
  mutate(gender_age = paste(gender, age)) %>% 
  filter(!str_detect(gender_age, "unknown")) %>% 
  filter(!str_detect(gender_age, "13-17")) %>% 
  complete(gender, age, fill = list(percentage = 0)) %>% 
  group_by(id, gender, page_name) %>% 
  summarize(percentage = sum(percentage)) %>% 
  ungroup()

library(highcharter)

dat <- gender_targeted_plot %>% 
  mutate(percentage = percentage * 100) %>% 
  data_to_boxplot(percentage, page_name, gender) 


highchart() %>%
  hc_xAxis(type = "category") %>%
  hc_add_series_list(dat)%>%
  hc_yAxis(reversed = F, min = 0, title = list(text = "% Audience of Ad"))  %>% 
  hc_chart(inverted = TRUE)


age_targeted_plot <- age_gender_targeted  %>% 
  filter(page_name %in% dutch_parties) %>% 
  mutate(date_range_start = as.Date(ad_delivery_start_time)) %>%
  filter(date_range_start >= as.Date("2020-09-01")) %>% 
  mutate(percentage = as.numeric(percentage)) %>% 
  mutate(gender_age = paste(gender, age)) %>% 
  filter(!str_detect(gender_age, "unknown")) %>% 
  filter(!str_detect(gender_age, "13-17")) %>% 
  complete(gender, age, fill = list(percentage = 0)) %>% 
  group_by(id, age, page_name) %>% 
  summarize(percentage = sum(percentage)) %>% 
  ungroup()


dat <- age_targeted_plot %>% 
  data_to_boxplot(percentage, page_name, age)


highchart() %>%
  hc_xAxis(type = "category") %>%
  hc_add_series_list(dat)%>%
  hc_yAxis(reversed = F, min = 0, title = list(text = "€ spent on Ads"))  %>% 
  hc_chart(inverted = TRUE)
```

## Geo Maps

```{r}
age_gender_targeted_raw <- fb_dat %>% 
  mutate(start_time = lubridate::as_datetime(ad_delivery_start_time) %>% lubridate::floor_date("day")) %>% 
  mutate(start_time = as.Date(start_time))

unnest_geos <- function(x) {
  cat(glue::glue("{x$row_number} out of {nrow(age_gender_targeted_raw)} ({round(100*x$row_number/nrow(age_gender_targeted_raw), 2)}%)\n\n"))
  x %>% 
  pull(region_distribution) %>% 
  flatten() %>% 
  map_dfr(flatten) %>% 
  mutate(id = x$id)%>% 
  mutate(start_time = x$start_time)%>% 
  mutate(page_name = x$page_name)
}

geo_targeted <- age_gender_targeted_raw %>% 
  mutate(row_number = 1:n()) %>% 
  # slice(1:10) %>% 
  split(1:nrow(.)) %>% 
  map_dfr(unnest_geos) 


dutch_regions <- geo_targeted %>% 
  count(region, sort = T) %>% 
  slice(1:12) %>% pull(region)

region_targeted_plot <- geo_targeted  %>% 
  filter(start_time >= as.Date("2020-09-01")) %>% 
  filter(page_name %in% dutch_parties) %>% 
  filter(region %in% dutch_regions) %>% 
  mutate(percentage = as.numeric(percentage)) %>% 
  complete(region, fill = list(percentage = 0)) %>% 
  group_by(id, region, page_name) %>% 
  summarize(percentage = sum(percentage)) %>% 
  ungroup()

library(highcharter)

dat <- region_targeted_plot %>% 
  data_to_boxplot(percentage, page_name, region)

highchart() %>%
  hc_xAxis(type = "category") %>%
  hc_add_series_list(dat)%>%
  hc_yAxis(reversed = F, min = 0, title = list(text = "€ spent on Ads"))  %>% 
  hc_chart(inverted = TRUE)
```
```{r}
require(dplyr)

mapdata <- get_data_from_map(download_map_data("https://code.highcharts.com/mapdata/countries/nl/nl-all.js"))

json_map <- download_map_data("https://code.highcharts.com/mapdata/countries/nl/nl-all.js")

glimpse(mapdata)

hcmap(mapdata)

highchart(type = "map") %>%
  hc_add_series(mapData = mapdata, showInLegend = FALSE)

highchart(type = "map") %>%
  hc_chart(backgroundColor = "#161C20") %>%
  hc_add_series(
    mapData = mapdata,
    showInLegend = FALSE,
    nullColor = "#424242",
    borderWidth = 0
  )

data_fake <- mapdata %>%
  select(code = `hc-a2`) %>%
  mutate(value = 1e5 * abs(rt(nrow(.), df = 10)))

glimpse(data_fake)
```


```{r}
final_map_dat <- mapdata %>% 
  left_join(region_targeted_plot %>% 
              rename(name = region,
                     advertiser_name = page_name) %>% 
              # filter(page_name == "D66") %>% 
              group_by(name, advertiser_name) %>% 
              summarize(percentage = median(percentage, na.rm = T)) %>% 
              mutate(name = ifelse(name == "North Brabant", "Noord-Brabant", name))) %>% 
  mutate(percentage = round(100*percentage, 2)) %>% 
  ungroup() %>% 
  left_join(color_dat) %>% 
  rename(colorful = color)

tidytemplate::save_it(final_map_dat)

library(httr)
library(jsonlite)

ausgeojson <- fromJSON("https://code.highcharts.com/mapdata/countries/nl/nl-all.geo.json")
  content() %>%
  # jsonlite::from()
  # read_json()
  fromJSON(simplifyVector = FALSE)# %>%
  as.json()

chart_maps <- function(x) {
  hcmap(
  "https://code.highcharts.com/mapdata/countries/nl/nl-all.js",
  data = x,
  value = "percentage",
  joinBy = c("name", "name"),
  name = "Median Ad Audience",
  dataLabels = list(enabled = TRUE, format = "{point.name}"),
  borderColor = "#FAFAFA",
  borderWidth = 0.1,
  tooltip = list(
    valueDecimals = 2,
    valueSuffix = "%"
    )
  ) %>% 
  hc_colorAxis(
    minColor = "white",
    maxColor = unique(x$colorful)
  )%>% 
    hc_title(
      text = unique(x$advertiser_name)
    ) %>%
    hc_exporting(
      enabled = TRUE
    )
}

ausgeojson

ausmap <- highchart(type = "map") %>%
  hc_add_series(mapData = ausgeojson, showInLegend = FALSE)
ausmap %>% list

fb_aggr <- readRDS("data/fb_aggr.RDS")
 
fb_aggr$map_data <- final_map_dat

tidytemplate::save_it(fb_aggr)

final_map_dat %>% 
  filter(advertiser_name %in% c("D66", "SP", "VVD")) %>% 
  group_split(advertiser_name) %>% 
  map(chart_maps) %>% hw_grid(ncol = 3)
```


```{r}
library(highcharter)

      hc_dat <- fb_aggr$times  %>%
        filter(advertiser_name %in% dutch_parties) 
      
      hc_dat %>% 
        hchart("line", hcaes(x = date_range_start, 
                             y = n, 
                             group = page_name,
                             color = color)) %>%
        hc_yAxis(
          align = "left",
          title = list(text = "Number of Ads")
        ) %>%
        hc_xAxis(
          align = "left",
          title = list(text = "Start Date of Ad")
        ) 
```
```{r}
library(tidyverse)
fb_dat %>% 
  unnest_wider(impressions)
```


```{r}
library(apexcharter)


hc_dat  %>% 
  apex(type = "line", mapping = aes(x = date_range_start, 
                             y = n, 
                             group = advertiser_name,
                             color = color))  %>% 
  ax_colors(unique(hc_dat$color)) %>% list
```


```{r}
fb_dat %>% count(currency)
```


## Conclusion