---
title: '`r readRDS("data/trans_dutch.rds")$dashboard_title`'
output:
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: scroll
    smooth_scroll: true
    theme: lumen
    logo: https://politieke-advertenties.nl/wp-content/uploads/2020/11/logo-e1604404707339.png
    favicon: https://politieke-advertenties.nl/wp-content/uploads/2020/11/logo-e1604404707339.png
runtime: shiny_prerendered
---


<!-- <style>                      -->
<!-- .sidebar { -->
<!--   font-family: Arial, sans-serif -->
<!-- } -->
<!-- .navbar { -->
<!--   font-family: Arial, sans-serif -->
<!-- } -->
<!-- </style -->

```{r global, include=FALSE, echo=F, context="setup", results='hide'}


library(flexdashboard)
knitr::opts_chunk$set(echo = F, message = F, warning = F)

library(shiny)
library(janitor)
library(DT)
library(magrittr)
library(glue)
library(highcharter)
library(lubridate)
library(knitr)
library(shinyWidgets)
library(tidyverse)
library(htmltools)
library(shinyBS)
# library(shinyjs)
# library(shinyalert)
# library(apexcharter)

# observe({
#    showNotification("This might take a few seconds to load.")
#  }) 



# ggl_ads <- readRDS("data/ggl_ads.RDS")

ggl_aggr <- readRDS("data/ggl_aggr.rds")
fb_aggr <- readRDS("data/fb_aggr.rds")

update_time <- read_lines("data/last_updated.txt") %>% 
  .[length(.)]


# 
# saveRDS(trans_eng, file = "data/trans_eng.rds")
# 
# trans_dutch <- translation %>% 
#   select(text_id, contains("dutch")) %>%
#   data.table::transpose() %>% 
#   janitor::row_to_names(1)
# 
# saveRDS(trans, file = "data/trans_dutch.rds")

# trans <- readRDS("data/trans_eng.rds")

# snap_ads <- readRDS("data/snap_ads.RDS")
# 
trans <- readRDS("data/trans_dutch.rds")
# 
# 
map_data <- readRDS("data/mapdata.RDS")

# trans <- read_csv2("data/translation.csv")  %>%
#   select(text_id, contains("dutch")) %>%
#   data.table::transpose() %>%
#   janitor::row_to_names(1) %>%
#   mutate_all(str_trim)%>%
#   mutate_all(~str_replace_all(.x, ", ", ",")) 


source("helpers.R")


### Facebook setup
dutch_parties_fb <- c("VVD", "D66", "FvD", "SP", "GroenLinks", "Volt Nederland", "PvdA", "CDA", "PvdD", "ChristenUnie")

advertiser_names_fb <- fb_aggr$times %>%
  # filter(advertiser_name %in% more_than_5_fb) %>% 
  pull(advertiser_name) %>% 
  unique() %>% 
  ## only keep national political parties
  keep(~magrittr::is_in(.x, dutch_parties_fb))

defaults_fb <- advertiser_names_fb %>% 
  keep(~magrittr::is_in(.x, dutch_parties_fb))

```




```{r, eval = F}
# Return the UI for a modal dialog with data selection input. If 'failed' is
# TRUE, then display a message that the previous value was invalid.
dataModal <- function(selected_lang = "Nederlands") {
      
if(selected_lang == "English"){
   trans_internal <- read_csv2("data/translation.csv")  %>%
      select(text_id, contains("english")) %>%
      data.table::transpose() %>%
      janitor::row_to_names(1)
    
    selected_lang <<- "English"
    
  } else if (selected_lang == "Nederlands") {
   trans_internal <- read_csv2("data/translation.csv")  %>%
      select(text_id, contains("dutch")) %>%
      data.table::transpose() %>%
      janitor::row_to_names(1)
    
    selected_lang <<- "Nederlands"
  }   
      
      modalDialog(
        h3(trans_internal$welcome_title),
        shiny::p(trans_internal$welcome_text),
        footer = tagList(
          radioGroupButtons(
   inputId = "language",
   choices = c("Nederlands", 
    "English"),
   selected = selected_lang,
   justified = TRUE
), 
modalButton("OK")
        )
      )
    }



trans <- reactive({
  
if(!length(input$language)==0){
  if(input$language == "English"){
    print("english")
    read_csv2("data/translation.csv")  %>%
      select(text_id, contains("english")) %>%
      data.table::transpose() %>%
      janitor::row_to_names(1)
    
    selected_lang <<- "English"
    
  } else if (input$language == "Nederlands") {
    print("dutch")
    read_csv2("data/translation.csv")  %>%
      select(text_id, contains("dutch")) %>%
      data.table::transpose() %>%
      janitor::row_to_names(1)
    
    selected_lang <<- "Nederlands"
  }   
} else {
    print("first dutch")
    read_csv2("data/translation.csv")  %>%
      select(text_id, contains("dutch")) %>%
      data.table::transpose() %>%
      janitor::row_to_names(1)  
}

})
```


```{r, context = "server"}


    # # Show modal when button is clicked.
    # observeEvent(input$show, {
    #   showModal(dataModal())
    # })

observe({
# shinyalert(
#     title = "Welcome to Dutch Election Observatory Dashboard",
#     text = "Note: the data shown in this dashboard is based on the platform's respective ad libraries. For this reason they might not show the full picture all political ads that were targeted at voters.",
#     size = "s",
#     closeOnEsc = TRUE,
#     closeOnClickOutside = FALSE,
#     html = FALSE,
#     type = "info",
#     showConfirmButton = TRUE,
#     showCancelButton = FALSE,
#     confirmButtonText = "OK",
#     confirmButtonCol = "#AEDEF4",
#     timer = 0,
#     imageUrl = "",
#     animation = TRUE
#   )
  # trans <- readRDS("data/trans_dutch.rds")
  
  # Sys.sleep(1)
  sendSweetAlert(session, title = trans$welcome_title,
    text = trans$welcome_text)
  #     if(!exists("selected_lang")){
  #       selected_lang <<- "Nederlands"
  #     }
  # showModal(dataModal(selected_lang))
  
 }) 


```


Facebook {data-icon="fa-facebook-square"}
=========================================

<!-- Metrics {data-icon="fa-facebook-square" data-navmenu="Facebook"} -->
<!-- ========================================= -->

Sidebar {.sidebar}
-------------------------------

```{r}


prettyRadioButtons(
   inputId = "plot_type_fb",
   label = trans$plot_type,
   choices = unlist_it(trans$choices), 
   selected = unlist_it(trans$choices, 1),
   # icon = icon("check"), 
   status = "info",
   animation = "smooth"
)


radioTooltip(id = "plot_type_fb", 
             choice = unlist_it(trans$choices, 1), 
             title = trans$choice_number_tooltip_fb)

radioTooltip(id = "plot_type_fb", 
             choice = unlist_it(trans$choices, 2), 
             title = trans$choice_spent_tooltip_fb)

radioTooltip(id = "plot_type_fb", 
             choice = unlist_it(trans$choices, 3), 
             title = trans$choice_impressions_tooltip_fb)

radioTooltip(id = "plot_type_fb", 
             choice = unlist_it(trans$choices, 4), 
             title = trans$choice_targeted_tooltip_fb)


selectInput("plot_type_sub_fb",
       label =  trans$total_vs_overtime,
       choices = unlist_it(trans$total_text),
       selected = unlist_it(trans$total_text, 1))



selectizeInput("advertisers__fb", trans$select_advertisers, 
            choices = advertiser_names_fb, 
            selected = defaults_fb, multiple = T,
            # selectize = TRUE, 
            width = NULL, 
            size = NULL)




```


```{r, eval = F}
useShinyjs(rmd = TRUE)


disabled(actionButton("standard_sel_btn_fb", "Standard selection", class = "btn-info btn-xs"))


observeEvent (req(!identical(input$advertisers__fb, defaults_fb)),{
  
  print("enable button")

shinyjs::enable("standard_sel_btn_fb")

})

observeEvent (req(identical(input$advertisers__fb, defaults_fb)),{
  
  print("disable button")

shinyjs::disable("standard_sel_btn_fb")
  
})


bsTooltip("standard_sel_btn_fb", "Show standard selection of advertisers (Dutch national parties).")

observeEvent (input$standard_sel_btn_fb,{

       updateSelectizeInput(
            session,
            inputId = "advertisers__fb",
            choices = advertiser_names_fb, 
            selected = defaults_fb)
       
})



facebook_links <- fb_aggr$total %>%
  mutate(advertiser_id = ifelse(is.na(advertiser_id), "No Advertiser ID", advertiser_id)) %>% 
  mutate(Link = paste0("https://www.facebook.com/", advertiser_id)) %>% 
  mutate(Link = ifelse(is.na(advertiser_id), "No Link", Link)) %>% 
  select(`Advertiser ID` = advertiser_id,
         `Advertiser Name` = advertiser_name,
         `Link` = Link
         ) 

 output$fb_links <-  DT::renderDataTable({

    facebook_links %>% 
     DT::datatable()
  })

actionButton("show_links_fb", "Show Links to Advertisers", class = "btn-info btn-xs", icon = icon("table"))

# renderUI({
  bsModal("fb_links", "Data Table", trigger = "show_links_fb", size = "large", dataTableOutput("fb_links"))
# })


```




Column 
-----------------------------------------------------------------------

### `r trans$fb_title`

```{r, context = "server"}

observe ({
  if(input$plot_type_fb %in% unlist_it(trans$choices, 1:3)){
    print(input$plot_type_fb)
    ## if any of the the first three choice options
    if (input$plot_type_sub_fb == unlist_it(trans$total_text, 2)){
      ## if current selection is over time update select input to over time default
      print("Over Time")

       updateSelectInput(session = session,
            inputId = "plot_type_sub_fb",
            label = trans$total_vs_overtime,
            choices = unlist_it(trans$total_text),
            selected = unlist_it(trans$total_text, 2))
    }
    else {
      ## if current selection is not over time update select input to total default
      print("Total")
      
     updateSelectInput(session = session,
          inputId = "plot_type_sub_fb",
          label = trans$total_vs_overtime,
          choices = unlist_it(trans$total_text),
          selected = unlist_it(trans$total_text, 1))
    }
    
  } else if(!input$plot_type_sub_fb == unlist_it(trans$choices, 4)) {
    print(input$plot_type_fb)
    print(input$plot_type_sub_fb)
      print("if targeted ads")
    ## if not any of the the first three choice options
    if(input$plot_type_sub_fb %in% unlist_it(trans$total_text)){
      ## if currently total vs. over time
      print("switch to targeting")
       updateSelectInput(session = session,
            inputId = "plot_type_sub_fb",
            label = trans$targeted_ads,
            choices = unlist_it(trans$targeted_ads_choices),
            selected = unlist_it(trans$targeted_ads_choices, 1))   
    } else if(input$plot_type_sub_fb==unlist_it(trans$targeted_ads_choices, 3)) {
    ## if geotargeting update to three 
    print(input$plot_type_sub_fb)
    print("update to only three advertisers")
       
      updateSelectizeInput(
        session,
        inputId = "advertisers__fb",
        choices = advertiser_names_fb, 
        selected = defaults_fb[1:3]) 
    }
      
  }




})

 output$fb_chart <-  shiny::renderUI({

    fb_aggr %>%
      hc_plotter(filters = input$advertisers__fb,
             plot_type = input$plot_type_fb,
             plot_type_sub = input$plot_type_sub_fb,
             mapdata = map_data,
             platform = "Facebook",
             trans_internal = trans,
             last_updated = update_time)
  })


# debugonce(hc_ggl)

# hc_plotter <- possibly(hc_plotter, otherwise = NULL, quiet = F)

 # ggl_aggr$times %>%
 #   group_by(advertiser_name) %>%
 #   arrange(date_range_start) %>%
 #   mutate(cumsum_n = cumsum(n)) %>%
 #   filter(advertiser_name %in% advertiser_names_fb) %>%
 #   ggplot(aes(date_range_start, cumsum_n, color = advertiser_name)) +
 #   geom_line()
 #   count(advertiser_name, sort = T)
```


```{r}


htmlOutput('fb_chart')

  # fb_aggr %>%
  #   hc_plotter(filters = "D66",
  #          plot_type = "Targeted Ads",
  #          plot_type_sub = "Geo targeting",
  #          platform = "Facebook")
# debugonce(hc_plotter)
# 
#   fb_aggr %>%
#     hc_plotter(filters = c("D66", "GroenLinks"),
#            plot_type = unlist_it(trans$choices, 4),
#            plot_type_sub = unlist_it(trans$targeted_ads_choices, 1),
#            # targeting = "Geotargeting",
#            platform = "Facebook")
  # 

```




Google Ads {data-icon="fa-google"}
=========================================

Sidebar {.sidebar}
-------------------------------

```{r}
prettyRadioButtons(
   inputId = "plot_type_ggl",
   label = trans$plot_type,
   choices = trans$choices %>% str_split(",") %>% unlist, 
   selected = trans$choices %>% str_split(",") %>% unlist %>% .[1],
   # icon = icon("check"), 
   status = "info",
   animation = "smooth"
)



radioTooltip(id = "plot_type_ggl", 
             choice = unlist_it(trans$choices, 1), 
             title = trans$choice_number_tooltip_ggl)

radioTooltip(id = "plot_type_ggl", 
             choice = unlist_it(trans$choices, 2), 
             title = trans$choice_spent_tooltip_ggl)

radioTooltip(id = "plot_type_ggl", 
             choice = unlist_it(trans$choices, 3), 
             title = trans$choice_impressions_tooltip_ggl)

radioTooltip(id = "plot_type_ggl", 
             choice = unlist_it(trans$choices, 4), 
             title = trans$choice_targeted_tooltip_ggl)

dutch_parties <- c("D66", "VVD", "GroenLinks", "SP", "Volt Nederland", "CDA", "PvdA", "FvD")


advertiser_names_ggl <- ggl_aggr$total %>%
  pull(advertiser_name) %>% 
  keep(~magrittr::is_in(.x, dutch_parties))

defaults_ggl <- advertiser_names_ggl %>% 
  keep(~magrittr::is_in(.x, dutch_parties))


selectInput("plot_type_sub_ggl",
       label =  trans$total_vs_overtime,
       choices = unlist_it(trans$total_text),
       selected = unlist_it(trans$total_text, 1))



selectizeInput("advertisers__ggl", trans$select_advertisers, 
            choices = advertiser_names_ggl, 
            selected = defaults_ggl, multiple = T,
            # selectize = TRUE, 
            width = NULL, 
            size = NULL)
```


```{r, eval = F}
disabled(actionButton("standard_sel_btn_ggl", "Standard selection", class = "btn-info btn-xs"))


observeEvent (req(!identical(input$advertisers__ggl, defaults_ggl)),{
  

shinyjs::enable("standard_sel_btn_ggl")

})

observeEvent (req(identical(input$advertisers__ggl, defaults_ggl)),{

shinyjs::disable("standard_sel_btn_ggl")
  


})


bsTooltip("standard_sel_btn_ggl", "Show standard selection of advertisers (Dutch national parties).")

observeEvent (input$standard_sel_btn_ggl,{

       updateSelectizeInput(
            session,
            inputId = "advertisers__ggl",
            choices = advertiser_names_ggl, 
            selected = defaults_ggl)
       
})
```

Column 
-----------------------------------------------------------------------

### `r trans$ggl_title`

```{r, context = "server"}


observe ({
  if(input$plot_type_ggl %in% unlist_it(trans$choices, 1:3)){
    print(input$plot_type_ggl)
    ## if any of the the first three choice options
    if (input$plot_type_sub_ggl == unlist_it(trans$total_text, 2)){
      ## if current selection is over time update select input to over time default
      print("Over Time")

       updateSelectInput(session = session,
            inputId = "plot_type_sub_ggl",
            label = trans$total_vs_overtime,
            choices = unlist_it(trans$total_text),
            selected = unlist_it(trans$total_text, 2))
    }
    else {
      ## if current selection is not over time update select input to total default
      print("Total")
      
     updateSelectInput(session = session,
          inputId = "plot_type_sub_ggl",
          label = trans$total_vs_overtime,
          choices = unlist_it(trans$total_text),
          selected = unlist_it(trans$total_text, 1))
    }
    
  } else if(!input$plot_type_sub_ggl == unlist_it(trans$choices, 4)) {
    print(input$plot_type_ggl)
    print(input$plot_type_sub_ggl)
      print("if targeted ads")
    ## if not any of the the first three choice options
    if(input$plot_type_sub_ggl %in% unlist_it(trans$total_text)){
      ## if currently total vs. over time
      print("switch to targeting")
       updateSelectInput(session = session,
            inputId = "plot_type_sub_ggl",
            label = trans$targeted_ads,
            choices = unlist_it(trans$targeted_ads_choices),
            selected = unlist_it(trans$targeted_ads_choices, 1))   
    } 
      
  }




})

# debugonce(hc_ggl)

hc_plotter <- possibly(hc_plotter, otherwise = NULL, quiet = F)


 output$ggl_chart <-  shiny::renderUI({
  
  ggl_aggr %>% 
    hc_plotter(filters = input$advertisers__ggl,
           plot_type = input$plot_type_ggl,
           plot_type_sub = input$plot_type_sub_ggl,
           platform = "Google",
             trans_internal = trans,
             last_updated = update_time)
  })

# ggl_aggr$ggl_times

  # ggl_aggr %>%
  #   hc_plotter(filters = dutch_parties,
  #               plot_type = "Targeted Ads",
  #               plot_type_sub = "Gender targeting",
  #              platform = "Google") %>% list
  
#     ggl_aggr %>%
#     hc_plotter(filters = c("D66", "GroenLinks", "FvD"),
#            plot_type = unlist_it(trans$choices, 2),
#            plot_type_sub = unlist_it(trans$total_text, 1),
#            platform = "Google",
#              trans_internal = trans,
#              last_updated = update_time)
# # 
# debugonce(hc_plotter)
#
# #   ggl_aggr %>% 
# #     hc_aggr_ggl(lvls, filters = defaults_ggl)
#   
#   hc_data %>%
#         hchart("line", hcaes(x = date_range_start, 
#                              y = n, 
#                              group = advertiser_name,
#                              color = color))
  
  # disabled
```

```{r}

htmlOutput('ggl_chart')   
```


Snapchat {data-icon="fa-snapchat-ghost"}
=========================================

<!-- Column {.tabset .tabset-fade} -->
<!-- ----------------------------------------------------------------------- -->

### `r trans$snap_title`

```{r}
HTML(trans$snap_message)
```



<!-- ```{r} -->


<!-- ad_counts <- snap_ads  %>%  -->
<!--   count(start_date, paying_advertiser_name) %>% -->
<!--   mutate(start_date = as.Date(start_date)) %>%  -->
<!--   complete(paying_advertiser_name, start_date = seq.Date(min(start_date), max(start_date), by="day"), fill = list(n = 0)) -->

<!-- ad_counts %>%  -->
<!--   hchart("line", hcaes(x = start_date, y = n, group = paying_advertiser_name)) %>% -->
<!--     hc_title( -->
<!--       text = "" -->
<!--     ) %>% -->
<!--     hc_yAxis( -->
<!--       align = "left", -->
<!--       title = list(text = "Number of Ads") -->
<!--     ) %>%  -->
<!--     hc_xAxis( -->
<!--       align = "left", -->
<!--       title = list(text = "Start Date of Ad") -->
<!--     ) %>%  -->
<!--     hc_exporting( -->
<!--       enabled = TRUE -->
<!--     )  -->
<!-- ``` -->


<!-- ### Ad Impressions -->


<!-- ```{r} -->


<!-- ad_impressions <- snap_ads  %>%  -->
<!--   group_by(start_date, paying_advertiser_name) %>%  -->
<!--   summarize(n = n(), -->
<!--             impressions = sum(impressions)) %>%  -->
<!--   mutate(start_date = lubridate::as_date(start_date))  -->

<!-- hchart( -->
<!--   ad_impressions,  -->
<!--   "bubble",  -->
<!--   hcaes( -->
<!--     x = start_date, -->
<!--     y = n,  -->
<!--     size = impressions, -->
<!--     group = paying_advertiser_name -->
<!--     ),  -->
<!-- maxSize = '10%' -->
<!--   ) %>% -->
<!--     hc_title( -->
<!--       text = "" -->
<!--     ) %>% -->
<!--     hc_yAxis( -->
<!--       align = "left", -->
<!--       title = list(text = "Number of Ads") -->
<!--     ) %>%  -->
<!--     hc_xAxis( -->
<!--       align = "left", -->
<!--       title = list(text = "Start Date of Ad") -->
<!--     ) %>%  -->
<!--     hc_exporting( -->
<!--       enabled = TRUE -->
<!--     )  -->
<!-- ``` -->
