---
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    anchor_sections: false
---

```{r global, include=FALSE, echo=F, context="setup", results='hide'}


library(flexdashboard)
knitr::opts_chunk$set(echo = F, message = F, warning = F)

library(shiny)
library(janitor)
library(DT)
library(magrittr)
library(glue)
library(highcharter)
library(lubridate)
library(knitr)
library(tidyverse)
library(htmltools)
library(shinyWidgets)



# ggl_ads <- readRDS("data/ggl_ads.RDS")

ggl_aggr <- readRDS("data/ggl_aggr.rds")
fb_aggr <- readRDS("data/fb_aggr.rds") 

# fb_aggr$total

update_time <- read_lines("data/last_updated.txt") %>% 
  .[length(.)]


# 
# saveRDS(trans_eng, file = "data/trans_eng.rds")
# 
# trans_dutch <- translation %>% 
#   select(text_id, contains("dutch")) %>%
#   data.table::transpose() %>% 
#   janitor::row_to_names(1)
# 
# saveRDS(trans, file = "data/trans_dutch.rds")

# trans_eng <- translation %>%
#   select(text_id, contains("english")) %>%
#   data.table::transpose() %>%
#   janitor::row_to_names(1)

# saveRDS(trans, file = "data/trans_eng.rds")

# snap_ads <- readRDS("data/snap_ads.RDS")
# 
trans <- readRDS("data/trans_dutch.rds")
# trans <- readRDS("data/trans_eng.rds")
# 
# 

# trans <- read_csv2("data/translation.csv")  %>%
#   select(text_id, contains("dutch")) %>%
#   data.table::transpose() %>% #glimpse
#   janitor::row_to_names(1) %>%
#   mutate_all(str_trim)%>%
#   mutate_all(~str_replace_all(.x, ", ", ","))


source("helpers.R")


### Facebook setup
dutch_parties_fb <- c("VVD", "D66", "FvD", "SP", "GroenLinks", "Volt Nederland", "PvdA", "CDA", "PvdD", "ChristenUnie", "SGP", "DENK")

advertiser_names_fb <- fb_aggr$times %>%
  distinct(advertiser_name) %>% 
  # filter(advertiser_name %in% more_than_5_fb) %>% 
  dplyr::pull(advertiser_name) %>% 
  ## only keep national political parties
  keep(~magrittr::is_in(.x, dutch_parties_fb))

defaults_fb <- advertiser_names_fb %>% 
  keep(~magrittr::is_in(.x, dutch_parties_fb))


dutch_parties <- c("D66", "VVD",
                   "GroenLinks", "SP", 
                   "Volt Nederland", "CDA", 
                   "PvdA", "FvD")

advertiser_names_ggl <- ggl_aggr$total %>%
  pull(advertiser_name) %>% 
  keep(~magrittr::is_in(.x, dutch_parties))  %>% 
  discard(~magrittr::is_in(.x, c( "FvD")))


defaults_ggl <- advertiser_names_ggl %>% 
  keep(~magrittr::is_in(.x, dutch_parties))

observe({
# shinyalert(
#     title = "Welcome to Dutch Election Observatory Dashboard",
#     text = "Note: the data shown in this dashboard is based on the platform's respective ad libraries. For this reason they might not show the full picture all political ads that were targeted at voters.",
#     size = "s",
#     closeOnEsc = TRUE,
#     closeOnClickOutside = FALSE,
#     html = FALSE,
#     type = "info",
#     showConfirmButton = TRUE,
#     showCancelButton = FALSE,
#     confirmButtonText = "OK",
#     confirmButtonCol = "#AEDEF4",
#     timer = 0,
#     imageUrl = "",
#     animation = TRUE
#   )
  # trans <- readRDS("data/trans_dutch.rds")
  
  # Sys.sleep(1)
  sendSweetAlert(session, 
                 title = trans$welcome_title,
                 text = tags$span(
                   trans$welcome_text_one,
                   tags$a(trans$welcome_text_two,     href="https://politieke-advertenties.nl/waar-komen-onze-data-vandaan/", target="_blank"), 
                   trans$welcome_text_three,
                   tags$br(),
                   tags$br(),
                   trans$welcome_text_four), html = T)
  #     if(!exists("selected_lang")){
  #       selected_lang <<- "Nederlands"
  #     }
  # showModal(dataModal(selected_lang))
  
 }) 

```



## Total Unique Ads {.tabset .tabset-fade .tabset-pills}

### Facebook Platforms (incl. Instagram)

```{r}
  fb_aggr %>% 
    hc_plotter(filters = dutch_parties_fb,
           plot_type = unlist_it(trans$choices, 1),
           plot_type_sub = unlist_it(trans$total_text, 1),
           platform = "Facebook",
           trans_internal = trans,
           last_updated = update_time
    )
```

### Google Platforms (incl. YouTube)

```{r}
  ggl_aggr %>% 
    hc_plotter(filters = dutch_parties,
           plot_type = unlist_it(trans$choices, 1),
           plot_type_sub = unlist_it(trans$total_text, 1),
           platform = "Google",
           trans_internal = trans,
           last_updated = update_time
    )
```


## Over Time Unique Ads {.tabset .tabset-fade .tabset-pills}

### Facebook Platforms (incl. Instagram)

```{r}
  fb_aggr %>% 
    hc_plotter(filters = dutch_parties,
           plot_type = unlist_it(trans$choices, 1),
           plot_type_sub = unlist_it(trans$total_text, 2),
           platform = "Facebook",
           trans_internal = trans,
           last_updated = update_time
    )
```

### Google Platforms (incl. YouTube)

```{r}
  ggl_aggr %>% 
    hc_plotter(filters = dutch_parties,
           plot_type = unlist_it(trans$choices, 1),
           plot_type_sub = unlist_it(trans$total_text, 2),
           platform = "Google",
           trans_internal = trans,
           last_updated = update_time
    )
```
